In [11]:

####### Code uses an iris dataset and randomforrest classifier to train the dataset and 
###### classify the flower species on the test dataset

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
iris = load_iris()
print type(iris)
print iris.data
print iris.feature_names
df=pd.DataFrame(iris.data, columns=iris.feature_names)
print "+++++++++++++++++++++"
print df.head()
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
print df.head(5)
df['is_train'] = np.random.uniform(0, 1, len(df)) <= 2.0/3.0
df.head()
train, test = df[df['is_train']==True], df[df['is_train']==False]
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))
features = df.columns[:4]
print "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
print len(train.columns)
print "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
print train['species']
y = pd.factorize(train['species'])[0]

<class 'sklearn.datasets.base.Bunch'>
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0

In [5]:
float(2.0/3.0)
clear all


SyntaxError: invalid syntax (<ipython-input-5-a4c93340ee3e>, line 2)

In [3]:
2.0/3.0


0.6666666666666666

In [8]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= 2.0/3.0

In [9]:
df['is_train']

0       True
1       True
2       True
3       True
4       True
5      False
6       True
7       True
8       True
9      False
10      True
11      True
12      True
13      True
14      True
15      True
16     False
17      True
18     False
19     False
20      True
21      True
22      True
23      True
24     False
25     False
26     False
27      True
28      True
29     False
       ...  
120     True
121     True
122     True
123     True
124    False
125    False
126     True
127    False
128     True
129    False
130     True
131    False
132     True
133     True
134     True
135     True
136    False
137    False
138    False
139     True
140     True
141    False
142     True
143     True
144    False
145     True
146     True
147     True
148    False
149    False
Name: is_train, dtype: bool